server:
  port: 8020

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          non_contextual_creation: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PASSWORD}

  main:
    allow-bean-definition-overriding: true