spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      authentication-database: ${AUTH_DATABASE}
      username: ${DB_USER}
      password: ${DB_PASS}
      database: ${DB_DATABASE}
      host: ${DB_HOST}
      port: ${DB_PORT}
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PASSWORD}
