version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: felixholfelder/led-rest
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run:
          name: Clean, Install
          command: ./mvnw clean install
      - run:
          name: Build Jar-File
          command: ./mvnw -Dmaven.test.skip=true package
      - store_artifacts:
          path: /home/circleci/project/target
      - persist_to_workspace:
          root: .
          paths:
            - .
  dockerize:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: ./
      - checkout
      - setup_remote_docker
      - run:
          name: Build latest docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Build versioned docker image
          command: |
            docker build -t $IMAGE_NAME:v$CIRCLE_BUILD_NUM .
      - run:
          name: Push to Docker-Hub
          command: |
            echo "$DOCKERHUB_PASS" |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:v$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: /home/circleci/project
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-pipeline:
    jobs:
      - build
      - dockerize:
          requires:
            - build