package led.rest.enums
enum class ColorModeEnum(var modeName: String, var modeId: Int) {
    FX_MODE_BLINK("Blink", 1),
    FX_MODE_BREATH("Atmen", 2),
    FX_MODE_COLOR_WIPE("Color Wipe",3),
    FX_MODE_COLOR_WIPE_INV("Color Wipe Inv", 4),
    FX_MODE_COLOR_WIPE_REV("Color Wipe Rev", 5),
    FX_MODE_COLOR_WIPE_REV_INV("Color Wipe Rev Inv",6),
    FX_MODE_COLOR_WIPE_RANDOM("Color Wipe zufällig", 7),
    FX_MODE_RANDOM_COLOR("Farbe zufällig", 8),
    FX_MODE_SINGLE_DYNAMIC("Einzeln Dynamisch", 9),
    FX_MODE_MULTI_DYNAMIC("Multi Dynamisch", 10),
    FX_MODE_RAINBOW("Regenbogen", 11),
    FX_MODE_RAINBOW_CYCLE("Regenbogen Kreis", 12),
    FX_MODE_SCAN("Scan", 13),
    FX_MODE_DUAL_SCAN("Dualer Scan", 14),
    FX_MODE_FADE("Fade", 15),
    FX_MODE_THEATER_CHASE("Theater", 16),
    FX_MODE_THEATER_CHASE_RAINBOW("Theater Regenbogen", 17),
    FX_MODE_RUNNING_LIGHTS("Laufend", 18),
    FX_MODE_TWINKLE("Sternchen", 19),
    FX_MODE_TWINKLE_RANDOM("Sternchen zufällig", 20),
    FX_MODE_TWINKLE_FADE("Sternchen Fade", 21),
    FX_MODE_TWINKLE_FADE_RANDOM("Sternchen Fade zufällig", 22),
    FX_MODE_SPARKLE("Funkeln", 23),
    FX_MODE_FLASH_SPARKLE("Funkekln Flash", 24),
    FX_MODE_HYPER_SPARKLE("Hyper Funkeln", 25),
    FX_MODE_STROBE("Stroboskop", 26),
    FX_MODE_STROBE_RAINBOW("Stroboskop Regenbogen", 27),
    FX_MODE_MULTI_STROBE("Multi-Stroboskop", 28),
    FX_MODE_BLINK_RAINBOW("Regenboben blinken", 29),
    FX_MODE_CHASE_WHITE("Weiß", 30),
    FX_MODE_CHASE_COLOR("Farbe", 31),
    FX_MODE_CHASE_RANDOM("Zufall", 32),
    FX_MODE_CHASE_RAINBOW("Regenbogen", 33),
    FX_MODE_CHASE_FLASH("Flash", 34),
    FX_MODE_CHASE_FLASH_RANDOM("Flash Zufall", 35),
    FX_MODE_CHASE_RAINBOW_WHITE("Weißer Regenbogen", 36),
    FX_MODE_CHASE_BLACKOUT("Schwarz ausgehend", 37),
    FX_MODE_CHASE_BLACKOUT_RAINBOW("Regenbogen ausgehend", 38),
    FX_MODE_COLOR_SWEEP_RANDOM("Wischen zufällig", 39),
    FX_MODE_RUNNING_COLOR("Laufende Farbe", 40),
    FX_MODE_RUNNING_RED_BLUE("Rot-Blau laufend", 41),
    FX_MODE_RUNNING_RANDOM("Zufällig laufend", 42),
    FX_MODE_LARSON_SCANNER("Scanner", 43),
    FX_MODE_COMET("Komet", 44),
    FX_MODE_FIREWORKS("Feuerwerk", 45),
    FX_MODE_FIREWORKS_RANDOM("Feuerwerk zufällig", 46),
    FX_MODE_MERRY_CHRISTMAS("Weihnachten", 47),
    FX_MODE_FIRE_FLICKER("Feuer", 48),
    FX_MODE_FIRE_FLICKER_SOFT("Leichtes Feuer", 49),
    FX_MODE_FIRE_FLICKER_INTENSE("Intensives Feuer", 50),
    FX_MODE_CIRCUS_COMBUSTUS("Zirkus", 51),
    FX_MODE_HALLOWEEN("Halloween", 52),
    FX_MODE_BICOLOR_CHASE("BICOLOR", 53),
    FX_MODE_TRICOLOR_CHASE("TRICOLOR", 54),
    FX_MODE_TWINKLEFOX("TWINKLEFOX", 55),
    FX_MODE_RAIN("Regen", 56)
}